name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Clean Gradle caches and build APK
      run: |
        # Delete local Gradle cache
        rm -rf ~/.gradle/caches/
        # Clean project and force refresh dependencies
        ./gradlew clean assembleDebug --refresh-dependencies

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecureMsg-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
